# Generated by Django 4.2.2 on 2023-08-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='none', max_length=50, verbose_name='type'),
        ),
    ]
